from setuptools import find_packages, setup


setup(
    name="dage",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "accelerate==0.27.2",
        "albumentations",
        "boto3>=1.37.22",
        "datasets",
        "decord",
        "diffusers==0.30.2",
        "einops",
        "evo",
        "fire",
        "h5py",
        "kornia",
        "matplotlib",
        "mediapy",
        "moviepy",
        "numpy==1.26.4",
        "omegaconf",
        "opencv-python",
        "pandas",
        "peft<0.14",
        "pyliblzfse",
        "roma",
        "scikit-image",
        "scipy",
        "segmentation_models_pytorch",
        "tokenizers==0.15.2",
        "setuptools",
        "tabulate",
        "tensorboard",
        "transformers==4.37.2",
        "trimesh",
        "utils3d @ git+https://github.com/EasternJournalist/utils3d.git@3913c65d81e05e47b9f367250cf8c0f7462a0900",
        "viser",
        "wandb",
        "xformers==0.0.24",
    ],
    python_requires=">=3.10",
)
