from setuptools import find_packages, setup


setup(
    name="dage",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "accelerate",
        "albumentations",
        "boto3",
        "datasets",
        "decord",
        "diffusers",
        "einops",
        "evo",
        "fire",
        "h5py",
        "kornia",
        "matplotlib",
        "mediapy",
        "moviepy",
        "numpy",
        "omegaconf",
        "opencv-python",
        "pandas",
        "peft<0.14",
        "pyliblzfse",
        "roma",
        "scikit-image",
        "scipy",
        "segmentation_models_pytorch",
        "tokenizers",
        "setuptools",
        "tabulate",
        "tensorboard",
        "transformers",
        "trimesh",
        "utils3d @ git+https://github.com/EasternJournalist/utils3d.git@3913c65d81e05e47b9f367250cf8c0f7462a0900",
        "viser",
        "wandb",
    ],
    python_requires=">=3.10",
)
